"""empty message

Revision ID: 01545762bd51
Revises: 079a16070cce
Create Date: 2018-08-01 10:42:40.902038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01545762bd51'
down_revision = '079a16070cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dipendente', sa.Column('immagine_profilo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dipendente', 'immagine_profilo')
    # ### end Alembic commands ###
