"""empty message

Revision ID: 079a16070cce
Revises: 8b93720020af
Create Date: 2018-07-18 17:02:59.607947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079a16070cce'
down_revision = '8b93720020af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preventivo', sa.Column('note', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preventivo', 'note')
    # ### end Alembic commands ###
