"""empty message

Revision ID: 0a62ae206e51
Revises: 
Create Date: 2018-05-15 11:28:15.071731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a62ae206e51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria_lavorazione',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('dipendente_registrato',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('fittizio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username', 'password')
    )
    op.create_table('pertinenza_lavorazione',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('clienteAccolto',
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cognome', sa.String(length=30), nullable=False),
    sa.Column('indirizzo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('difficolta', sa.String(length=30), nullable=False),
    sa.Column('tipologia', sa.String(length=30), nullable=False),
    sa.Column('referenza', sa.String(length=30), nullable=False),
    sa.Column('sopraluogo', sa.Boolean(), nullable=False),
    sa.Column('datasopraluogo', sa.Date(), nullable=True),
    sa.Column('lavorazione', sa.String(length=500), nullable=False),
    sa.Column('commerciale', sa.String(length=60), nullable=False),
    sa.Column('tecnico', sa.String(length=60), nullable=True),
    sa.Column('capocantiere', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['capocantiere'], ['dipendente_registrato.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commerciale'], ['dipendente_registrato.username'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico'], ['dipendente_registrato.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('nome', 'cognome', 'indirizzo')
    )
    op.create_table('dipendente',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('cf', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cognome', sa.String(length=30), nullable=False),
    sa.Column('dataNascita', sa.Date(), nullable=False),
    sa.Column('residenza', sa.String(length=120), nullable=False),
    sa.Column('domicilio', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('email_aziendale', sa.String(length=50), nullable=False),
    sa.Column('email_personale', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=30), nullable=True),
    sa.Column('partitaIva', sa.String(length=30), nullable=True),
    sa.Column('classe', sa.String(length=30), nullable=False),
    sa.Column('dirigente', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['username', 'password'], ['dipendente_registrato.username', 'dipendente_registrato.password'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('cf'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('settore_lavorazione',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('pertinenza', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pertinenza'], ['pertinenza_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('dirigente',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('notifica',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=60), nullable=False),
    sa.Column('contenuto', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'titolo')
    )
    op.create_table('dipendente_fittizio',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('classe', sa.String(length=20), nullable=False),
    sa.Column('dirigente', sa.Boolean(), nullable=False),
    sa.Column('creatoreCredenziali', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['creatoreCredenziali'], ['dirigente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['username', 'password'], ['dipendente_registrato.username', 'dipendente_registrato.password'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('impegni',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('testo', sa.String(length=500), nullable=False),
    sa.Column('dirigente', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dirigente'], ['dirigente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impegni')
    op.drop_table('dipendente_fittizio')
    op.drop_table('notifica')
    op.drop_table('dirigente')
    op.drop_table('settore_lavorazione')
    op.drop_table('dipendente')
    op.drop_table('clienteAccolto')
    op.drop_table('pertinenza_lavorazione')
    op.drop_table('dipendente_registrato')
    op.drop_table('categoria_lavorazione')
    # ### end Alembic commands ###
