"""empty message

Revision ID: 166c3ebb9897
Revises: 5f2c408f334b
Create Date: 2018-09-05 21:31:46.935919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '166c3ebb9897'
down_revision = '5f2c408f334b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendario', sa.Column('descrizione', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendario', 'descrizione')
    # ### end Alembic commands ###
