"""empty message

Revision ID: 1cf69bfd0494
Revises: 166c3ebb9897
Create Date: 2018-09-06 10:36:02.781907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cf69bfd0494'
down_revision = '166c3ebb9897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendario', sa.Column('id_evento', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendario', 'id_evento')
    # ### end Alembic commands ###
