"""empty message

Revision ID: 2bce9aca3259
Revises: e3cb891690df
Create Date: 2018-10-15 11:23:23.803053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bce9aca3259'
down_revision = 'e3cb891690df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigiano', sa.Column('contatti1', sa.String(length=20), nullable=True))
    op.add_column('artigiano', sa.Column('contatti2', sa.String(length=20), nullable=True))
    op.drop_column('artigiano', 'contatti')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artigiano', sa.Column('contatti', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('artigiano', 'contatti2')
    op.drop_column('artigiano', 'contatti1')
    # ### end Alembic commands ###
