"""empty message

Revision ID: 2f347651bd71
Revises: ed74e5173833
Create Date: 2018-10-02 09:37:36.864614

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2f347651bd71'
down_revision = 'ed74e5173833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modello_prodotto_prezzario', sa.Column('posaPerc', sa.Integer(), nullable=True))
    op.drop_column('modello_prodotto_prezzario', 'nettoUsFornituraPosa')
    op.drop_column('modello_prodotto_prezzario', 'prezzoListinoFornituraPosa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modello_prodotto_prezzario', sa.Column('prezzoListinoFornituraPosa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('modello_prodotto_prezzario', sa.Column('nettoUsFornituraPosa', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('modello_prodotto_prezzario', 'posaPerc')
    # ### end Alembic commands ###
