"""empty message

Revision ID: 30f144dccca1
Revises: 5711eb4afcc9
Create Date: 2018-05-05 16:43:40.514344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f144dccca1'
down_revision = '5711eb4afcc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clienteAccolto',
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cognome', sa.String(length=30), nullable=False),
    sa.Column('indirizzo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('difficolta', sa.String(length=30), nullable=False),
    sa.Column('tipologia', sa.String(length=30), nullable=False),
    sa.Column('referenza', sa.String(length=30), nullable=False),
    sa.Column('sopraluogo', sa.Boolean(), nullable=False),
    sa.Column('datasopraluogo', sa.Date(), nullable=True),
    sa.Column('lavorazione', sa.String(length=500), nullable=False),
    sa.Column('commerciale', sa.String(length=60), nullable=False),
    sa.Column('tecnico', sa.String(length=60), nullable=True),
    sa.Column('capocantiere', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['capocantiere'], ['dipendente_registrato.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commerciale'], ['dipendente_registrato.username'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico'], ['dipendente_registrato.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('nome', 'cognome', 'indirizzo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clienteAccolto')
    # ### end Alembic commands ###
