"""empty message

Revision ID: 3208bd60f7aa
Revises: 9692ffa862f4
Create Date: 2019-02-28 10:19:05.620227

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3208bd60f7aa'
down_revision = '9692ffa862f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contabilita_cantiere', sa.Column('nome_lav', sa.String(length=1000), nullable=True))
    op.drop_column('contabilita_cantiere', 'costi_effettivi_budget_imprevisti')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contabilita_cantiere', sa.Column('costi_effettivi_budget_imprevisti', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('contabilita_cantiere', 'nome_lav')
    # ### end Alembic commands ###
