"""empty message

Revision ID: 32081f5d9bd4
Revises: 2583383d1c2d
Create Date: 2019-03-01 17:02:12.252440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32081f5d9bd4'
down_revision = '2583383d1c2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imprevisti',
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=10), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('costo_fattura', sa.Float(), nullable=True),
    sa.Column('nome_artigiano', sa.String(length=60), nullable=True),
    sa.Column('impiego_artigiano', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['nome_artigiano', 'impiego_artigiano'], ['artigiano.nominativo', 'artigiano.impiego'], ),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.revisione', 'preventivo.tipologia'], ),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imprevisti')
    # ### end Alembic commands ###
