"""empty message

Revision ID: 4f25d00b54cc
Revises: 64b1fcc629ed
Create Date: 2019-03-10 13:17:04.029574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f25d00b54cc'
down_revision = '64b1fcc629ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente_accolto', sa.Column('cap', sa.String(length=10), nullable=True))
    op.add_column('cliente_accolto', sa.Column('civico', sa.String(length=6), nullable=True))
    op.add_column('cliente_accolto', sa.Column('regione', sa.String(length=120), nullable=True))
    op.add_column('cliente_accolto', sa.Column('via', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente_accolto', 'via')
    op.drop_column('cliente_accolto', 'regione')
    op.drop_column('cliente_accolto', 'civico')
    op.drop_column('cliente_accolto', 'cap')
    # ### end Alembic commands ###
