"""empty message

Revision ID: 52f13fd97a36
Revises: 
Create Date: 2018-05-16 16:55:53.903155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f13fd97a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pertinenza_lavorazione',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('clienteAccolto',
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cognome', sa.String(length=30), nullable=False),
    sa.Column('indirizzo', sa.String(length=120), nullable=False),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('difficolta', sa.String(length=30), nullable=False),
    sa.Column('tipologia', sa.String(length=30), nullable=False),
    sa.Column('referenza', sa.String(length=30), nullable=False),
    sa.Column('sopraluogo', sa.Boolean(), nullable=False),
    sa.Column('datasopraluogo', sa.Date(), nullable=True),
    sa.Column('lavorazione', sa.String(length=500), nullable=False),
    sa.Column('commerciale', sa.String(length=60), nullable=False),
    sa.Column('tecnico', sa.String(length=60), nullable=True),
    sa.Column('capocantiere', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['capocantiere'], ['dipendente_registrato.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['commerciale'], ['dipendente_registrato.username'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['tecnico'], ['dipendente_registrato.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('nome', 'cognome', 'indirizzo')
    )
    op.create_table('settore_lavorazione',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('prezzario_edile',
    sa.Column('tipologia_lavorazione', sa.String(length=100), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('pertinenza', sa.String(length=100), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=True),
    sa.Column('prezzoMin', sa.Integer(), nullable=True),
    sa.Column('prezzoMax', sa.Integer(), nullable=True),
    sa.Column('dimensione', sa.String(length=100), nullable=True),
    sa.Column('fornitura', sa.Integer(), nullable=True),
    sa.Column('posa', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('daVerificare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['categoria'], ['categoria_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pertinenza'], ['categoria_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settore'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('settore', 'tipologia_lavorazione')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prezzario_edile')
    op.drop_table('settore_lavorazione')
    op.drop_table('clienteAccolto')
    op.drop_table('pertinenza_lavorazione')
    # ### end Alembic commands ###
