"""empty message

Revision ID: 54580b9f6bba
Revises: 9a50363952d2
Create Date: 2018-10-11 12:12:32.025222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54580b9f6bba'
down_revision = '9a50363952d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prezzario_edile_pertinenza_fkey', 'prezzario_edile', type_='foreignkey')
    op.create_foreign_key(None, 'prezzario_edile', 'settore_lavorazione', ['pertinenza'], ['nome'], onupdate='CASCADE', ondelete='SET DEFAULT')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prezzario_edile', type_='foreignkey')
    op.create_foreign_key('prezzario_edile_pertinenza_fkey', 'prezzario_edile', 'settore_lavorazione', ['pertinenza'], ['nome'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
