"""empty message

Revision ID: 5f2c408f334b
Revises: e4d402282e60
Create Date: 2018-09-03 10:19:14.254154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2c408f334b'
down_revision = 'e4d402282e60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messaggio',
    sa.Column('mittente', sa.String(length=60), nullable=False),
    sa.Column('destinatario', sa.String(length=60), nullable=False),
    sa.Column('testo', sa.String(length=1000), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ora', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['destinatario'], ['dirigente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mittente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mittente', 'destinatario', 'data', 'ora')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messaggio')
    # ### end Alembic commands ###
