"""empty message

Revision ID: 64b1fcc629ed
Revises: 32081f5d9bd4
Create Date: 2019-03-01 17:06:19.349297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b1fcc629ed'
down_revision = '32081f5d9bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamenti_cliente',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('totale_prev_edile', sa.Float(), nullable=True),
    sa.Column('totale_prev_finiture', sa.Float(), nullable=True),
    sa.Column('totale_prev_varianti', sa.Float(), nullable=True),
    sa.Column('acconto', sa.Float(), nullable=True),
    sa.Column('acconto_pagato', sa.Boolean(), nullable=True),
    sa.Column('prima_rata', sa.Float(), nullable=True),
    sa.Column('prima_rata_pagata', sa.Boolean(), nullable=True),
    sa.Column('seconda_rata', sa.Float(), nullable=True),
    sa.Column('seconda_rata_pagata', sa.Boolean(), nullable=True),
    sa.Column('terza_rata', sa.Float(), nullable=True),
    sa.Column('terza_rata_pagata', sa.Boolean(), nullable=True),
    sa.Column('saldo', sa.Integer(), nullable=True),
    sa.Column('saldo_pagato', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('numero_preventivo')
    )
    op.create_table('imprevisti',
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=10), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('costo_fattura', sa.Float(), nullable=True),
    sa.Column('nome_artigiano', sa.String(length=60), nullable=True),
    sa.Column('impiego_artigiano', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['nome_artigiano', 'impiego_artigiano'], ['artigiano.nominativo', 'artigiano.impiego'], ),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.revisione', 'preventivo.tipologia'], ),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine')
    )
    op.create_table('contabilita_cantiere',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('nome_lav', sa.String(length=1000), nullable=True),
    sa.Column('nome_artigiano', sa.String(length=60), nullable=True),
    sa.Column('impiego_artigiano', sa.String(length=60), nullable=True),
    sa.Column('ordine_lav', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('costi_effettivi', sa.Float(), nullable=True),
    sa.Column('fattura', sa.Float(), nullable=True),
    sa.Column('budget_imprevisti', sa.Float(), nullable=True),
    sa.Column('fattura_budget_imprevisti', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['nome_artigiano', 'impiego_artigiano'], ['artigiano.nominativo', 'artigiano.impiego'], ),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia', 'ordine_lav'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.tipologia', 'lavorazione_preventivo_edile.ordine'], ),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'tipologia', 'ordine_lav')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contabilita_cantiere')
    op.drop_table('imprevisti')
    op.drop_table('pagamenti_cliente')
    # ### end Alembic commands ###
