"""empty message

Revision ID: 6688bebc009d
Revises: 
Create Date: 2019-02-19 10:34:43.956070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6688bebc009d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lavorazione_edile',
    sa.Column('tipologia_lavorazione', sa.String(length=1000), nullable=False),
    sa.Column('settore', sa.String(length=200), nullable=False),
    sa.Column('pertinenza', sa.String(length=100), server_default='Non definito', nullable=True),
    sa.Column('unitaMisura', sa.String(length=10), nullable=True),
    sa.Column('prezzoMin', sa.Float(), nullable=True),
    sa.Column('prezzoMax', sa.Float(), nullable=True),
    sa.Column('dimensione', sa.String(length=100), nullable=True),
    sa.Column('fornitura', sa.Float(), nullable=True),
    sa.Column('posa', sa.Float(), nullable=True),
    sa.Column('ricaricoAzienda', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('daVerificare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pertinenza'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['settore'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('settore', 'tipologia_lavorazione')
    )
    op.create_table('assistenza_lavorazione',
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('prezzoPercentuale', sa.Boolean(), nullable=True),
    sa.Column('tipologia_lavorazione', sa.String(length=1000), nullable=False),
    sa.Column('settore', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tipologia_lavorazione', 'settore'], ['lavorazione_edile.tipologia_lavorazione', 'lavorazione_edile.settore'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nome', 'tipologia_lavorazione', 'settore')
    )
    op.create_foreign_key(None, 'lavorazione_preventivo_edile', 'lavorazione_edile', ['settore', 'tipologia_lavorazione'], ['settore', 'tipologia_lavorazione'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lavorazione_preventivo_edile', type_='foreignkey')
    op.drop_table('assistenza_lavorazione')
    op.drop_table('lavorazione_edile')
    # ### end Alembic commands ###
