"""empty message

Revision ID: 6acbbd52740e
Revises: 6b53269a29b1
Create Date: 2018-10-19 12:17:06.333598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acbbd52740e'
down_revision = '6b53269a29b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dipendente', sa.Column('domicilioCap', sa.Integer(), nullable=True))
    op.add_column('dipendente', sa.Column('domicilioCitta', sa.String(length=120), nullable=True))
    op.add_column('dipendente', sa.Column('domicilioNum', sa.Integer(), nullable=True))
    op.add_column('dipendente', sa.Column('domicilioRegione', sa.String(length=120), nullable=True))
    op.add_column('dipendente', sa.Column('domicilioVia', sa.String(length=120), nullable=True))
    op.add_column('dipendente', sa.Column('residenzaCap', sa.Integer(), nullable=True))
    op.add_column('dipendente', sa.Column('residenzaCitta', sa.String(length=120), nullable=False))
    op.add_column('dipendente', sa.Column('residenzaNum', sa.Integer(), nullable=False))
    op.add_column('dipendente', sa.Column('residenzaRegione', sa.String(length=120), nullable=False))
    op.add_column('dipendente', sa.Column('residenzaVia', sa.String(length=120), nullable=False))
    op.drop_column('dipendente', 'residenza')
    op.drop_column('dipendente', 'domicilio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dipendente', sa.Column('domicilio', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('dipendente', sa.Column('residenza', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('dipendente', 'residenzaVia')
    op.drop_column('dipendente', 'residenzaRegione')
    op.drop_column('dipendente', 'residenzaNum')
    op.drop_column('dipendente', 'residenzaCitta')
    op.drop_column('dipendente', 'residenzaCap')
    op.drop_column('dipendente', 'domicilioVia')
    op.drop_column('dipendente', 'domicilioRegione')
    op.drop_column('dipendente', 'domicilioNum')
    op.drop_column('dipendente', 'domicilioCitta')
    op.drop_column('dipendente', 'domicilioCap')
    # ### end Alembic commands ###
