"""empty message

Revision ID: 9692ffa862f4
Revises: c020428afd33
Create Date: 2019-02-22 15:28:50.451696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9692ffa862f4'
down_revision = 'c020428afd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imprevisti',
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=10), nullable=True),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('costo', sa.Float(), nullable=True),
    sa.Column('costo_fattura', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.revisione', 'preventivo.tipologia'], ),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imprevisti')
    # ### end Alembic commands ###
