"""empty message

Revision ID: 9a50363952d2
Revises: 2f347651bd71
Create Date: 2018-10-09 12:57:46.751803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9a50363952d2'
down_revision = '2f347651bd71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'modello_prodotto_prezzario', 'tipologia_prodotto_prezzario', ['tipologia'], ['nome'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('prezzario_edile', 'costo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prezzario_edile', sa.Column('costo', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'modello_prodotto_prezzario', type_='foreignkey')
    # ### end Alembic commands ###
