"""empty message

Revision ID: afe2da9702aa
Revises: 52f13fd97a36
Create Date: 2018-05-18 09:26:49.614154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe2da9702aa'
down_revision = '52f13fd97a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settore_lavorazione',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('prezzario_edile',
    sa.Column('tipologia_lavorazione', sa.String(length=100), nullable=False),
    sa.Column('settore', sa.String(length=200), nullable=False),
    sa.Column('pertinenza', sa.String(length=100), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('costo', sa.Integer(), nullable=True),
    sa.Column('prezzoMin', sa.Integer(), nullable=True),
    sa.Column('prezzoMax', sa.Integer(), nullable=True),
    sa.Column('dimensione', sa.String(length=100), nullable=True),
    sa.Column('fornitura', sa.Integer(), nullable=True),
    sa.Column('posa', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('daVerificare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pertinenza'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settore'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('settore', 'tipologia_lavorazione')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prezzario_edile')
    op.drop_table('settore_lavorazione')
    # ### end Alembic commands ###
