"""empty message

Revision ID: b9cda2df49bf
Revises: 54580b9f6bba
Create Date: 2018-10-11 12:20:14.526718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9cda2df49bf'
down_revision = '54580b9f6bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prezzario_edile',
    sa.Column('tipologia_lavorazione', sa.String(length=500), nullable=False),
    sa.Column('settore', sa.String(length=200), nullable=False),
    sa.Column('pertinenza', sa.String(length=100), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('prezzoMin', sa.Float(), nullable=True),
    sa.Column('prezzoMax', sa.Float(), nullable=True),
    sa.Column('dimensione', sa.String(length=100), nullable=True),
    sa.Column('fornitura', sa.Float(), nullable=True),
    sa.Column('posa', sa.Float(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('daVerificare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['pertinenza'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='SET DEFAULT'),
    sa.ForeignKeyConstraint(['settore'], ['settore_lavorazione.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('settore', 'tipologia_lavorazione')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prezzario_edile')
    # ### end Alembic commands ###
