"""empty message

Revision ID: c020428afd33
Revises: 6688bebc009d
Create Date: 2019-02-19 11:51:51.956701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c020428afd33'
down_revision = '6688bebc009d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preventivo',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('data_ultima_modifica', sa.Date(), nullable=True),
    sa.Column('nome_cliente', sa.String(length=30), nullable=True),
    sa.Column('cognome_cliente', sa.String(length=30), nullable=True),
    sa.Column('indirizzo_cliente', sa.String(length=120), nullable=True),
    sa.Column('dipendente_generatore', sa.String(length=60), nullable=True),
    sa.Column('dipendente_ultimaModifica', sa.String(length=60), nullable=True),
    sa.Column('intervento_commessa', sa.String(length=130), nullable=True),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('stato', sa.Boolean(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ricarico_generale', sa.Integer(), nullable=True),
    sa.Column('ricarico_extra', sa.Integer(), nullable=True),
    sa.Column('sconto_totale', sa.Float(), nullable=True),
    sa.Column('tipologia_sconto_totale', sa.Integer(), nullable=True),
    sa.Column('iva_totale', sa.Integer(), nullable=True),
    sa.Column('budget_imprevisti', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_generatore'], ['dipendente.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dipendente_ultimaModifica'], ['dipendente.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nome_cliente', 'cognome_cliente', 'indirizzo_cliente'], ['cliente_accolto.nome', 'cliente_accolto.cognome', 'cliente_accolto.indirizzo'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['numero_preventivo', 'intervento_commessa'], ['commessa_preventivo.numero_preventivo', 'commessa_preventivo.intervento'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'tipologia', 'revisione')
    )
    op.create_table('capitolato_prodotto',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('modello', sa.String(length=100), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.Column('marchio', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['nome', 'modello', 'tipologia', 'marchio'], ['modello_prodotto_prezzario.prodotto', 'modello_prodotto_prezzario.nome', 'modello_prodotto_prezzario.tipologia', 'modello_prodotto_prezzario.marchio'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nome', 'modello', 'tipologia', 'marchio')
    )
    op.create_table('lavorazione_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=True),
    sa.Column('tipologia_lavorazione', sa.String(length=1000), nullable=True),
    sa.Column('nome_modificato', sa.String(length=1000), nullable=True),
    sa.Column('unitaMisura', sa.String(length=10), nullable=True),
    sa.Column('prezzoUnitario', sa.Float(), nullable=True),
    sa.Column('assistenza', sa.String(length=500), nullable=True),
    sa.Column('costo_assistenza', sa.Float(), nullable=True),
    sa.Column('tipo_costo_assistenza', sa.Boolean(), nullable=True),
    sa.Column('copia', sa.Boolean(), nullable=True),
    sa.Column('ordine_lav_originale', sa.Integer(), nullable=True),
    sa.Column('settore_lav_copia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia', 'ordine_lav_originale'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.tipologia', 'lavorazione_preventivo_edile.ordine'], onupdate='CASCADE'),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.revisione', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settore', 'tipologia_lavorazione'], ['lavorazione_edile.settore', 'lavorazione_edile.tipologia_lavorazione'], onupdate='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'tipologia', 'ordine')
    )
    op.create_table('lavorazione_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=True),
    sa.Column('tipologia_lavorazione', sa.String(length=500), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('prezzoUnitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.revisione', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'tipologia', 'ordine')
    )
    op.create_table('prodotto_preventivo_finiture',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia_preventivo', sa.String(length=20), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=True),
    sa.Column('nome_prodotto', sa.String(length=100), nullable=True),
    sa.Column('nome_modificato', sa.String(length=100), nullable=True),
    sa.Column('modello', sa.String(length=100), nullable=True),
    sa.Column('marchio', sa.String(length=100), nullable=True),
    sa.Column('codice', sa.String(length=100), nullable=True),
    sa.Column('quantita', sa.Float(), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('diffCapitolato', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia_preventivo'], ['preventivo.numero_preventivo', 'preventivo.revisione', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologia', 'nome_prodotto', 'modello', 'marchio'], ['modello_prodotto_prezzario.tipologia', 'modello_prodotto_prezzario.prodotto', 'modello_prodotto_prezzario.nome', 'modello_prodotto_prezzario.marchio'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'tipologia_preventivo', 'ordine')
    )
    op.create_table('contabilita_cantiere',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('ordine_lav', sa.Integer(), nullable=False),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('costi_effettivi', sa.Float(), nullable=True),
    sa.Column('fattura', sa.Float(), nullable=True),
    sa.Column('budget_imprevisti', sa.Float(), nullable=True),
    sa.Column('costi_effettivi_budget_imprevisti', sa.Float(), nullable=True),
    sa.Column('fattura_budget_imprevisti', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'tipologia', 'ordine_lav'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.tipologia', 'lavorazione_preventivo_edile.ordine'], ),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'tipologia', 'ordine_lav')
    )
    op.create_table('sottolavorazione_cad_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('prezzoBase', sa.Float(), nullable=True),
    sa.Column('ricarico', sa.Integer(), nullable=True),
    sa.Column('nome_modificato', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'tipologia', 'ordine_sottolavorazione')
    )
    op.create_table('sottolavorazione_cad_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.revisione', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_mc_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.Column('profondita', sa.Float(), nullable=True),
    sa.Column('prezzoBase', sa.Float(), nullable=True),
    sa.Column('ricarico', sa.Integer(), nullable=True),
    sa.Column('nome_modificato', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'tipologia', 'ordine_sottolavorazione')
    )
    op.create_table('sottolavorazione_mc_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.Column('profondita', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.revisione', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_ml_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('prezzoBase', sa.Float(), nullable=True),
    sa.Column('ricarico', sa.Integer(), nullable=True),
    sa.Column('nome_modificato', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_ml_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.revisione', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_mq_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.Column('prezzoBase', sa.Float(), nullable=True),
    sa.Column('ricarico', sa.Integer(), nullable=True),
    sa.Column('nome_modificato', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.revisione', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_mq_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('revisione', sa.Integer(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'revisione', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.revisione', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'revisione', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sottolavorazione_mq_preventivo_varianti')
    op.drop_table('sottolavorazione_mq_preventivo_edile')
    op.drop_table('sottolavorazione_ml_preventivo_varianti')
    op.drop_table('sottolavorazione_ml_preventivo_edile')
    op.drop_table('sottolavorazione_mc_preventivo_varianti')
    op.drop_table('sottolavorazione_mc_preventivo_edile')
    op.drop_table('sottolavorazione_cad_preventivo_varianti')
    op.drop_table('sottolavorazione_cad_preventivo_edile')
    op.drop_table('contabilita_cantiere')
    op.drop_table('prodotto_preventivo_finiture')
    op.drop_table('lavorazione_preventivo_varianti')
    op.drop_table('lavorazione_preventivo_edile')
    op.drop_table('capitolato_prodotto')
    op.drop_table('preventivo')
    # ### end Alembic commands ###
