"""empty message

Revision ID: d11d55ab4cc3
Revises: 
Create Date: 2018-09-24 04:29:32.581811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11d55ab4cc3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornitore',
    sa.Column('primo_gruppo', sa.String(length=150), nullable=False),
    sa.Column('sotto_gruppo', sa.String(length=150), nullable=False),
    sa.Column('settoreMerceologico', sa.String(length=150), nullable=True),
    sa.Column('stato', sa.String(length=100), nullable=True),
    sa.Column('tempiDiConsegna', sa.String(length=20), nullable=True),
    sa.Column('prezziNetti', sa.String(length=5), nullable=True),
    sa.Column('scontoStandard', sa.Integer(), nullable=True),
    sa.Column('scontoExtra1', sa.Integer(), nullable=True),
    sa.Column('scontroExtra2', sa.Integer(), nullable=True),
    sa.Column('trasporto', sa.Float(), nullable=True),
    sa.Column('imballo', sa.Float(), nullable=True),
    sa.Column('montaggio', sa.Float(), nullable=True),
    sa.Column('trasportoUnitaMisura', sa.String(length=8), nullable=True),
    sa.Column('imballoUnitaMisura', sa.String(length=8), nullable=True),
    sa.Column('montaggioUnitaMisura', sa.String(length=8), nullable=True),
    sa.Column('giorniPagamenti', sa.String(length=100), nullable=True),
    sa.Column('modalitaPagamenti', sa.String(length=100), nullable=True),
    sa.Column('tipologiaPagamenti', sa.String(length=100), nullable=True),
    sa.Column('provincia', sa.String(length=50), nullable=True),
    sa.Column('indirizzo', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('sito', sa.String(length=100), nullable=True),
    sa.Column('daVerificare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['giorniPagamenti'], ['giorni_pagamento_fornitore.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modalitaPagamenti'], ['modalita_pagamento_fornitore.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['settoreMerceologico'], ['settore_merceologico.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tempiDiConsegna'], ['tempi_di_consegna.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologiaPagamenti'], ['tipologia_pagamento_fornitore.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('primo_gruppo', 'sotto_gruppo')
    )
    op.create_table('personale_fornitore',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cognome', sa.String(length=100), nullable=False),
    sa.Column('azienda_primo_gruppo', sa.String(length=150), nullable=False),
    sa.Column('azienda_sotto_gruppo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('ruolo', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['azienda_primo_gruppo', 'azienda_sotto_gruppo'], ['fornitore.primo_gruppo', 'fornitore.sotto_gruppo'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nome', 'cognome', 'azienda_primo_gruppo', 'azienda_sotto_gruppo')
    )
    op.create_foreign_key(None, 'modello_prodotto_prezzario', 'fornitore', ['fornitore_primo_gruppo', 'fornitore_sotto_gruppo'], ['primo_gruppo', 'sotto_gruppo'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'modello_prodotto_prezzario', type_='foreignkey')
    op.drop_table('personale_fornitore')
    op.drop_table('fornitore')
    # ### end Alembic commands ###
