"""empty message

Revision ID: e18120394b9f
Revises: 
Create Date: 2018-07-17 08:47:38.662460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18120394b9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commessa_preventivo',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('intervento', sa.String(length=120), nullable=False),
    sa.Column('indirizzo', sa.String(length=120), nullable=True),
    sa.Column('comune', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('numero_preventivo', 'intervento')
    )
    op.create_table('preventivo',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('nome_cliente', sa.String(length=30), nullable=True),
    sa.Column('cognome_cliente', sa.String(length=30), nullable=True),
    sa.Column('indirizzo_cliente', sa.String(length=120), nullable=True),
    sa.Column('dipendente_generatore', sa.String(length=60), nullable=True),
    sa.Column('dipendente_ultimaModifica', sa.String(length=60), nullable=True),
    sa.Column('intervento_commessa', sa.String(length=130), nullable=True),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('stato', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente_generatore'], ['dipendente.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dipendente_ultimaModifica'], ['dipendente.username'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['nome_cliente', 'cognome_cliente', 'indirizzo_cliente'], ['cliente_accolto.nome', 'cliente_accolto.cognome', 'cliente_accolto.indirizzo'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['numero_preventivo', 'intervento_commessa'], ['commessa_preventivo.numero_preventivo', 'commessa_preventivo.intervento'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'tipologia')
    )
    op.create_table('lavorazione_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=True),
    sa.Column('tipologia_lavorazione', sa.String(length=500), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('prezzoUnitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.data', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'tipologia', 'ordine')
    )
    op.create_table('lavorazione_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('settore', sa.String(length=100), nullable=True),
    sa.Column('tipologia_lavorazione', sa.String(length=500), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('prezzoUnitario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.data', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'tipologia', 'ordine')
    )
    op.create_table('prodotto_preventivo_finiture',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.Column('nome_prodotto', sa.String(length=100), nullable=True),
    sa.Column('modello', sa.String(length=100), nullable=True),
    sa.Column('marchio', sa.String(length=100), nullable=True),
    sa.Column('codice', sa.String(length=100), nullable=True),
    sa.Column('quantita', sa.Float(), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('diffCapitolato', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'tipologia'], ['preventivo.numero_preventivo', 'preventivo.data', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologia', 'nome_prodotto', 'modello', 'marchio'], ['modello_prodotto_prezzario.tipologia', 'modello_prodotto_prezzario.prodotto', 'modello_prodotto_prezzario.nome', 'modello_prodotto_prezzario.marchio'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'tipologia', 'ordine')
    )
    op.create_table('sottolavorazione_cad_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.data', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'tipologia', 'ordine_sottolavorazione')
    )
    op.create_table('sottolavorazione_cad_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.data', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_mc_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.Column('profondita', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.data', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'tipologia', 'ordine_sottolavorazione')
    )
    op.create_table('sottolavorazione_mc_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.Column('profondita', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.data', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_ml_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.data', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_ml_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.data', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_mq_preventivo_edile',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_edile.numero_preventivo', 'lavorazione_preventivo_edile.data', 'lavorazione_preventivo_edile.ordine', 'lavorazione_preventivo_edile.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    op.create_table('sottolavorazione_mq_preventivo_varianti',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('ordine_sottolavorazione', sa.Integer(), nullable=False),
    sa.Column('tipologia', sa.String(length=20), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('larghezza', sa.Float(), nullable=True),
    sa.Column('altezza', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'ordine', 'tipologia'], ['lavorazione_preventivo_varianti.numero_preventivo', 'lavorazione_preventivo_varianti.data', 'lavorazione_preventivo_varianti.ordine', 'lavorazione_preventivo_varianti.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'ordine', 'ordine_sottolavorazione', 'tipologia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sottolavorazione_mq_preventivo_varianti')
    op.drop_table('sottolavorazione_mq_preventivo_edile')
    op.drop_table('sottolavorazione_ml_preventivo_varianti')
    op.drop_table('sottolavorazione_ml_preventivo_edile')
    op.drop_table('sottolavorazione_mc_preventivo_varianti')
    op.drop_table('sottolavorazione_mc_preventivo_edile')
    op.drop_table('sottolavorazione_cad_preventivo_varianti')
    op.drop_table('sottolavorazione_cad_preventivo_edile')
    op.drop_table('prodotto_preventivo_finiture')
    op.drop_table('lavorazione_preventivo_varianti')
    op.drop_table('lavorazione_preventivo_edile')
    op.drop_table('preventivo')
    op.drop_table('commessa_preventivo')
    # ### end Alembic commands ###
