"""empty message

Revision ID: e3cb891690df
Revises: 694a514eb4d7
Create Date: 2018-10-11 19:23:10.034330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3cb891690df'
down_revision = '694a514eb4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('impiego_artigiano',
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_table('artigiano',
    sa.Column('nominativo', sa.String(length=60), nullable=False),
    sa.Column('impiego', sa.String(length=60), nullable=False),
    sa.Column('valutazione', sa.Integer(), nullable=True),
    sa.Column('contatti', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['impiego'], ['impiego_artigiano.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nominativo', 'impiego')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artigiano')
    op.drop_table('impiego_artigiano')
    # ### end Alembic commands ###
