"""empty message

Revision ID: e4d402282e60
Revises: fc8c38ef0a85
Create Date: 2018-09-02 19:29:04.375006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d402282e60'
down_revision = 'fc8c38ef0a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('impegni', sa.Column('checkato', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('impegni', 'checkato')
    # ### end Alembic commands ###
