"""empty message

Revision ID: e8855f77cd65
Revises: abf3ee893622
Create Date: 2018-09-01 14:28:42.309446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8855f77cd65'
down_revision = 'abf3ee893622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifica',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=60), nullable=False),
    sa.Column('contenuto', sa.String(length=500), nullable=True),
    sa.Column('tipologia', sa.String(length=60), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'titolo', 'numero')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifica')
    # ### end Alembic commands ###
