"""empty message

Revision ID: ec8303dc1d2a
Revises: 017ecbad2ceb
Create Date: 2018-08-01 15:49:31.251092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8303dc1d2a'
down_revision = '017ecbad2ceb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendario',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=120), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('durata_giorni', sa.Integer(), nullable=True),
    sa.Column('luogo', sa.String(length=120), nullable=True),
    sa.Column('tipologia', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'start_date', 'titolo', 'tipologia')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendario')
    # ### end Alembic commands ###
