"""empty message

Revision ID: ed74e5173833
Revises: d11d55ab4cc3
Create Date: 2018-10-01 21:33:12.678193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed74e5173833'
down_revision = 'd11d55ab4cc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prodotto_prezzario',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tipologia'], ['tipologia_prodotto_prezzario.nome'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nome', 'tipologia')
    )
    op.create_table('modello_prodotto_prezzario',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('prodotto', sa.String(length=100), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.Column('marchio', sa.String(length=100), nullable=False),
    sa.Column('codice', sa.String(length=100), nullable=True),
    sa.Column('fornitore_primo_gruppo', sa.String(length=150), nullable=True),
    sa.Column('fornitore_sotto_gruppo', sa.String(length=150), nullable=True),
    sa.Column('prezzoListinoFornituraPosa', sa.Float(), nullable=True),
    sa.Column('prezzoListinoFornitura', sa.Float(), nullable=True),
    sa.Column('rincaroAzienda', sa.Integer(), nullable=True),
    sa.Column('trasportoAzienda', sa.Float(), nullable=True),
    sa.Column('imballoAzienda', sa.Float(), nullable=True),
    sa.Column('posa', sa.Float(), nullable=True),
    sa.Column('trasportoAziendaUnitaMisura', sa.String(length=8), nullable=True),
    sa.Column('imballoAziendaUnitaMisura', sa.String(length=8), nullable=True),
    sa.Column('nettoUsFornituraPosa', sa.Float(), nullable=True),
    sa.Column('nettoUsFornitura', sa.Float(), nullable=True),
    sa.Column('rincaroCliente', sa.Integer(), nullable=True),
    sa.Column('versoDiLettura', sa.Boolean(), nullable=True),
    sa.Column('daVerificare', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fornitore_primo_gruppo', 'fornitore_sotto_gruppo'], ['fornitore.primo_gruppo', 'fornitore.sotto_gruppo'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prodotto', 'tipologia'], ['prodotto_prezzario.nome', 'prodotto_prezzario.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nome', 'prodotto', 'tipologia', 'marchio')
    )
    op.create_table('capitolato_prodotto',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('modello', sa.String(length=100), nullable=False),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.Column('marchio', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['nome', 'modello', 'tipologia', 'marchio'], ['modello_prodotto_prezzario.prodotto', 'modello_prodotto_prezzario.nome', 'modello_prodotto_prezzario.tipologia', 'modello_prodotto_prezzario.marchio'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nome', 'modello', 'tipologia', 'marchio')
    )
    op.create_table('prodotto_preventivo_finiture',
    sa.Column('numero_preventivo', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('ordine', sa.Integer(), nullable=False),
    sa.Column('tipologia_preventivo', sa.String(length=20), nullable=True),
    sa.Column('tipologia', sa.String(length=100), nullable=False),
    sa.Column('nome_prodotto', sa.String(length=100), nullable=True),
    sa.Column('modello', sa.String(length=100), nullable=True),
    sa.Column('marchio', sa.String(length=100), nullable=True),
    sa.Column('codice', sa.String(length=100), nullable=True),
    sa.Column('quantita', sa.Float(), nullable=True),
    sa.Column('unitaMisura', sa.String(length=5), nullable=True),
    sa.Column('diffCapitolato', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['numero_preventivo', 'data', 'tipologia_preventivo'], ['preventivo.numero_preventivo', 'preventivo.data', 'preventivo.tipologia'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tipologia', 'nome_prodotto', 'modello', 'marchio'], ['modello_prodotto_prezzario.tipologia', 'modello_prodotto_prezzario.prodotto', 'modello_prodotto_prezzario.nome', 'modello_prodotto_prezzario.marchio'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('numero_preventivo', 'data', 'tipologia', 'ordine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prodotto_preventivo_finiture')
    op.drop_table('capitolato_prodotto')
    op.drop_table('modello_prodotto_prezzario')
    op.drop_table('prodotto_prezzario')
    # ### end Alembic commands ###
