"""empty message

Revision ID: f3b3352e3673
Revises: ed19c0e4d600
Create Date: 2018-09-06 11:53:20.243701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3b3352e3673'
down_revision = 'ed19c0e4d600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenda',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=300), nullable=True),
    sa.Column('giorno', sa.Date(), nullable=False),
    sa.Column('inizio_ora', sa.Time(), nullable=False),
    sa.Column('fine_ora', sa.Time(), nullable=True),
    sa.Column('cliente_sopraluogo', sa.String(length=60), nullable=True),
    sa.Column('accompagnatore_sopraluogo', sa.String(length=60), nullable=True),
    sa.Column('luogo_sopraluogo', sa.String(length=200), nullable=True),
    sa.Column('sopraluogo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'giorno', 'inizio_ora')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agenda')
    # ### end Alembic commands ###
