"""empty message

Revision ID: f485d21061ab
Revises: 9218db39286f
Create Date: 2018-04-29 22:03:45.090062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f485d21061ab'
down_revision = '9218db39286f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifiche',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=60), nullable=False),
    sa.Column('contenuto', sa.String(length=120), nullable=True),
    sa.Column('dirigente', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], ),
    sa.ForeignKeyConstraint(['dirigente'], ['dipendente.username'], ),
    sa.PrimaryKeyConstraint('dipendente', 'titolo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifiche')
    # ### end Alembic commands ###
