"""empty message

Revision ID: fc8c38ef0a85
Revises: e8855f77cd65
Create Date: 2018-09-02 10:29:20.059395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8c38ef0a85'
down_revision = 'e8855f77cd65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('richiesta_ferie',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'start_date')
    )
    op.create_table('notifica',
    sa.Column('destinatario', sa.String(length=60), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titolo', sa.String(length=60), nullable=True),
    sa.Column('contenuto', sa.String(length=500), nullable=True),
    sa.Column('tipologia', sa.String(length=60), nullable=True),
    sa.Column('richiedente_ferie', sa.String(length=60), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario'], ['dipendente.username'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['richiedente_ferie', 'start_date'], ['richiesta_ferie.dipendente', 'richiesta_ferie.start_date'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('destinatario', 'numero')
    )
    op.drop_table('richiestaFerie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('richiestaFerie',
    sa.Column('dipendente', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('titolo', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], name='richiestaFerie_dipendente_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dipendente', 'start_date', 'titolo', name='richiestaFerie_pkey')
    )
    op.drop_table('notifica')
    op.drop_table('richiesta_ferie')
    # ### end Alembic commands ###
