"""empty message

Revision ID: fdd5b4388887
Revises: 
Create Date: 2018-05-03 14:59:02.500095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd5b4388887'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dipendente_registrato',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('fittizio', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('password')
    )
    op.create_table('dipendente',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('cf', sa.String(length=16), nullable=False),
    sa.Column('nome', sa.String(length=30), nullable=False),
    sa.Column('cognome', sa.String(length=30), nullable=False),
    sa.Column('dataNascita', sa.Date(), nullable=False),
    sa.Column('residenza', sa.String(length=120), nullable=False),
    sa.Column('domicilio', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=12), nullable=False),
    sa.Column('email_aziendale', sa.String(length=50), nullable=False),
    sa.Column('email_personale', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=30), nullable=True),
    sa.Column('partitaIva', sa.String(length=30), nullable=True),
    sa.Column('classe', sa.String(length=30), nullable=False),
    sa.Column('dirigente', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['password'], ['dipendente_registrato.password'], ),
    sa.ForeignKeyConstraint(['username'], ['dipendente_registrato.username'], ),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('cf'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('dirigente',
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['dipendente.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('notifica',
    sa.Column('dipendente', sa.String(length=60), nullable=False),
    sa.Column('titolo', sa.String(length=60), nullable=False),
    sa.Column('contenuto', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['dipendente'], ['dipendente.username'], ),
    sa.PrimaryKeyConstraint('dipendente', 'titolo')
    )
    op.create_table('dipendente_fittizio',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('classe', sa.String(length=20), nullable=False),
    sa.Column('dirigente', sa.Boolean(), nullable=False),
    sa.Column('creatoreCredenziali', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['creatoreCredenziali'], ['dirigente.username'], ),
    sa.ForeignKeyConstraint(['username'], ['dipendente_registrato.username'], ),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dipendente_fittizio')
    op.drop_table('notifica')
    op.drop_table('dirigente')
    op.drop_table('dipendente')
    op.drop_table('dipendente_registrato')
    # ### end Alembic commands ###
